"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.DEFAULT_INDICATOR_BORDER_COLOR = exports.DEFAULT_INDICATOR_BACKGROUND_COLOR = exports.DEFAULT_INDICATOR_SIZE = exports.DEFAULT_CLOSE_BUTTON_CALLBACK = exports.DEFAULT_CLOSE_BUTTON_TEXT = exports.DEFAULT_DIRECTION = exports.DEFAULT_SAFE_INSET = void 0;
const DEFAULT_SAFE_INSET = 50;
exports.DEFAULT_SAFE_INSET = DEFAULT_SAFE_INSET;
const DEFAULT_DIRECTION = 'horizontal';
exports.DEFAULT_DIRECTION = DEFAULT_DIRECTION;
const DEFAULT_CLOSE_BUTTON_TEXT = 'close';
exports.DEFAULT_CLOSE_BUTTON_TEXT = DEFAULT_CLOSE_BUTTON_TEXT;

const DEFAULT_CLOSE_BUTTON_CALLBACK = () => {};

exports.DEFAULT_CLOSE_BUTTON_CALLBACK = DEFAULT_CLOSE_BUTTON_CALLBACK;
const DEFAULT_INDICATOR_SIZE = 40;
exports.DEFAULT_INDICATOR_SIZE = DEFAULT_INDICATOR_SIZE;
const DEFAULT_INDICATOR_BACKGROUND_COLOR = '#fff';
exports.DEFAULT_INDICATOR_BACKGROUND_COLOR = DEFAULT_INDICATOR_BACKGROUND_COLOR;
const DEFAULT_INDICATOR_BORDER_COLOR = '#fff';
exports.DEFAULT_INDICATOR_BORDER_COLOR = DEFAULT_INDICATOR_BORDER_COLOR;
//# sourceMappingURL=constants.js.map