declare const DEFAULT_SAFE_INSET = 50;
declare const DEFAULT_DIRECTION = "horizontal";
declare const DEFAULT_CLOSE_BUTTON_TEXT = "close";
declare const DEFAULT_CLOSE_BUTTON_CALLBACK: () => void;
declare const DEFAULT_INDICATOR_SIZE = 40;
declare const DEFAULT_INDICATOR_BACKGROUND_COLOR = "#fff";
declare const DEFAULT_INDICATOR_BORDER_COLOR = "#fff";
export { DEFAULT_SAFE_INSET, DEFAULT_DIRECTION, DEFAULT_CLOSE_BUTTON_TEXT, DEFAULT_CLOSE_BUTTON_CALLBACK, DEFAULT_INDICATOR_SIZE, DEFAULT_INDICATOR_BACKGROUND_COLOR, DEFAULT_INDICATOR_BORDER_COLOR, };
